### ISSUE TITLE
No `.sh` script to run playbooks ?

### ISSUE THREAD

**Issue by TristanMarion** [tbobm/machine-deploy#1]
Do you manually run every playbook ?
Or do you use a script that should be in the repo ?

**Comment by tbobm** [comment]
While in "development" phase, my playbooks are intended to be run manually, yep.

The goal is, of course, to automate the whole process, in addition to create a single playbook composed by multiple roles.

The current playbooks will be merge in a single one, with each of their name specifying the corresponding role. :)

**Comment by TristanMarion** [comment]
Thanks for the answer !
